# Generated by Django 4.2.3 on 2023-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisiments', '0002_advertisements_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisiments',
            name='image',
            field=models.ImageField(default='', upload_to='advertisiments/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
